@startuml usecase
left to right direction
skinparam actorStyle stick
skinparam packageStyle rectangle
skinparam shadowing false
actor "Developer" as Dev
actor "API User" as User

rectangle "PDF Generator Service" {
    usecase "Generate PDF" as UC_Generate
    usecase "Check Health" as UC_Health
    usecase "Browse API Docs" as UC_Docs
    usecase "Render PDF\nlocally (CLI)" as UC_CLI
}

Dev --> UC_Docs
Dev --> UC_CLI
Dev --> UC_Generate
Dev --> UC_Health

User --> UC_Generate
User --> UC_Health
User --> UC_Docs

@enduml
